"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2r_0c!gqwn3u@0p019ax8m0=-$z*lpil42r1#e)7^ssnfyw%nr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "second_project",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {},
    'sqlite3': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    "mongodb": {
        "ENGINE": "django_mongodb_backend",
        "HOST": os.environ.get(
            "MONGODB_URI",
            "mongodb://127.0.0.1:27017",
        ),
        "NAME": os.environ.get("MONGODB_NAME", "second_project"),
    }

}


# MongoDB validation pipeline dashboard targets.  The dashboard only reads
# these collections through Django's existing MongoDB connection.
DASHBOARD_MONGO_ALIAS = os.environ.get("DASHBOARD_MONGO_ALIAS", "mongodb")
DASHBOARD_SUCCESS_DATABASE = os.environ.get(
    "DASHBOARD_SUCCESS_DATABASE",
    "encore_legacy_success_experiment",
)
DASHBOARD_SUCCESS_COLLECTION = os.environ.get(
    "DASHBOARD_SUCCESS_COLLECTION",
    "records",
)
DASHBOARD_FAILURE_DATABASE = os.environ.get(
    "DASHBOARD_FAILURE_DATABASE",
    "encore_legacy_failure_experiment",
)
DASHBOARD_FAILURE_COLLECTION = os.environ.get(
    "DASHBOARD_FAILURE_COLLECTION",
    "records",
)
DASHBOARD_REPORT_DATABASE = os.environ.get(
    "DASHBOARD_REPORT_DATABASE",
    DASHBOARD_SUCCESS_DATABASE,
)
DASHBOARD_REPORT_COLLECTION = os.environ.get(
    "DASHBOARD_REPORT_COLLECTION",
    "pipeline_runs",
)
DASHBOARD_BRONZE_DATABASE = os.environ.get(
    "DASHBOARD_BRONZE_DATABASE",
    DASHBOARD_SUCCESS_DATABASE,
)
DASHBOARD_BRONZE_COLLECTION = os.environ.get(
    "DASHBOARD_BRONZE_COLLECTION",
    "bronze_raw_records",
)
DASHBOARD_SILVER_DATABASE = os.environ.get(
    "DASHBOARD_SILVER_DATABASE",
    DASHBOARD_SUCCESS_DATABASE,
)
DASHBOARD_SILVER_COLLECTIONS = {
    "silver_employee": os.environ.get(
        "DASHBOARD_SILVER_EMPLOYEE_COLLECTION",
        "silver_employee",
    ),
    "silver_area": os.environ.get(
        "DASHBOARD_SILVER_AREA_COLLECTION",
        "silver_area",
    ),
    "silver_parent_area": os.environ.get(
        "DASHBOARD_SILVER_PARENT_AREA_COLLECTION",
        "silver_parent_area",
    ),
    "silver_top_area_detail": os.environ.get(
        "DASHBOARD_SILVER_TOP_AREA_COLLECTION",
        "silver_top_area_detail",
    ),
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
